pipeline {
    agent any // Specify an agent if needed

    stages {
        stage('Build') {
            steps {
                sh 'docker build -t selenium-test-image selenium_NEW/.' // Build the Docker image
            }
        }

        stage('Run Tests') {
            steps {
                sh 'docker run selenium-test-image'
            }
        }
    }
}
