pipeline {
    agent any // Specify an agent if needed

    stages {
        stage('Build') {
            steps {
               
                sh 'docker build -t selenium-test-image selenium_NEW/.' // Build the Docker image
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    def container = docker.run(
                        image: 'selenium-test-image',
                       
                    )
                    container.waitExit() // Wait for the container to finish
                    if (container.exitCode != 0) {
                        error 'Tests failed!'
                    }
                }
            }
        }
    }
}
